[server]
runOnSave=true
enableStaticServing=true
headless=true

[theme]
base="light"
primaryColor="#2194fb"
secondaryBackgroundColor="#f0f0f0"
textColor="#333333"

[browser]
gatherUsageStats=false
serverAddress="localhost"

[client]
showSidebarNavigation=false